services:
  - type: web
    name: fixmate-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://fixmate-client-gamma.vercel.app
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true