require('dotenv').config()
const express = require('express')
const cors = require('cors')
const mongoose = require('mongoose')
const passport = require('passport')
const authRoutes = require('./routes/auth')
const profileRoutes = require('./routes/profile')
const paymentRoutes = require('./routes/payments')
const bookingRoutes = require('./routes/bookings')
const adminRoutes = require('./routes/admin')
const { startPlanExpiryJob } = require('./services/planExpiry')

const app = express()
app.use(cors({ origin: "*"}))
app.use('/api/payments/webhook', express.raw({ type: 'application/json' }))
app.use(express.json())
app.use(passport.initialize())
app.get("/", (_req, res) => res.send("FixMate API is running"))
app.get('/api/health', (_req, res) => res.json({ status: 'ok', service: 'fixmate-api' }))
app.use('/api/auth', authRoutes)
app.use('/api/profile', profileRoutes)
app.use('/api/payments', paymentRoutes)
app.use('/api/bookings', bookingRoutes)
app.use('/api/admin', adminRoutes)
app.use((error, _req, res, _next) => { console.error(error); res.status(500).json({ message: 'Something went wrong.' }) })

const port = process.env.PORT || 5000
mongoose.connect(process.env.MONGODB_URI).then(() => {
  startPlanExpiryJob()
  app.listen(port, () => console.log(`FixMate API running on http://localhost:${port}`))
}).catch((error) => { console.error('MongoDB connection failed:', error.message); process.exit(1) })
